# Generated by Django 3.1.3 on 2020-12-21 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20201217_2350'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movieId', models.IntegerField(default=-1)),
                ('title', models.CharField(max_length=200)),
                ('img', models.CharField(max_length=500)),
                ('year', models.IntegerField(default=1960)),
                ('main_genre', models.CharField(max_length=30)),
            ],
        ),
    ]
