# Generated by Django 3.1.3 on 2020-12-26 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_movie'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=-1)),
                ('item_id', models.IntegerField(default=-1)),
                ('imdbId', models.IntegerField(default=-1)),
                ('title', models.CharField(max_length=200)),
                ('img', models.CharField(max_length=500)),
                ('year', models.IntegerField(default=1960)),
                ('explanations', models.CharField(max_length=500)),
            ],
        ),
    ]
