# Generated by Django 3.1.3 on 2020-12-27 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_auto_20201227_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='user',
            field=models.IntegerField(default=-1),
        ),
    ]
